version: '3.8'
services:

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/database/data
    env_file:
      - ./db/.env
    ports:
      - 5432:5432

volumes:
    postgres_data: